name: Deployment

on:
  push:
    branches:
      - test
  


jobs:
  deployment:
    container:
      image: bitnami/kubectl
    runs-on: ubuntu-latest
    environment: kubexti
    steps:
      - name: get-config
        run: echo $KUBEXTI_CLUSTER_CONFIG >> ~/.kube/config; wc -l ~/.kube/config
        env:
          KUBEXTI_CLUSTER_CONFIG: ${{secrets.KUBEXTI_CLUSTER_CONFIG}}
