name: Deployment

on:
  push:
    branches:
      - test
  


jobs:
  deployment:
    container:
      image: bitnami/kubectl
    runs-on: ubuntu-latest
    environment: kubexti
    steps:
      - name: get-config
        run: mkdir ~/.kube/; echo "${KUBEXTI_CLUSTER_CONFIG}" >> ~/.kube/config; wc -l ~/.kube/config
        env:
          KUBEXTI_CLUSTER_CONFIG: |
            ${{ secrets.KUBEXTI_CLUSTER_CONFIG }}
      - name: whichconfig
        run: wc -l ~/.kube/config
        shell: bash
      - name: get-pods
        run: kubectl get pods
