name: Deployment

on:
  push:
    branches:
      - test
  


jobs:
  deployment:
    container:
      image: bitnami/kubectl
    runs-on: ubuntu-latest
    environment: kubexti
    steps:
      - name: get-config
        run: mkdir ~/.kube/; echo $TEST >> ~/.kube/config; wc -l ~/.kube/config
        env:
          TEST: ${{secrets.TEST}}
      - name: whichconfig
        run: wc -l ~/.kube/config
      - name: get-pods
        run: echo ~/.kube/config
