name: Deployment

on:
  workflow_call:
  
jobs:
  deployment:
    container:
      image: bitnami/kubectl
    runs-on: ubuntu-latest
    environment: ext-cluster
    steps:
      - name: get-config
        run: mkdir ~/.kube/; echo "${CLUSTER_CONFIG}" >> ~/.kube/config; wc -l ~/.kube/config
        env:
          CLUSTER_CONFIG: |
            ${{ secrets.CLUSTER_CONFIG }}
      - name: restart
        run: kubectl -n flight2cal rollout restart deployment flight2cal-frontend
