name: Deployment

on:
  push:
    branches:
      - test

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: kubexti
    steps:
      - name: get-config
        run: echo $TESTSECRET
        env:
          TESTSECRET: ${{secrets.TEST}}
